### ISSUE TITLE
4.0

### ISSUE THREAD

**Issue by ksassnowski** [ksassnowski/venture#54]
The development of version 4.0 happens in the [4.x branch](https://github.com/ksassnowski/venture/tree/4.x) of this repository.

## Todo

- [x] Implement Plugin System
- [x] Replace `vimeo/psalm` with `nunomaduro/larastan`
- [x] Define `WorkflowStepInterface` for workflow steps
- [x] Add gated jobs (see #32 for reference)
- [x] Add closure-based jobs (see #24) (968c26354d638fa5a8b3e7842a822344a803df67)
- [x] Add testing helpers to run the `then` and `catch` callbacks of a workflow (42231332e4d0504f4c01cfd14980750ab39550b8)
- [x] Add option to run all jobs of a workflow on a specific connection (804193ec60352110cd783e6a18897c0523376832)
- [x] Add plugin to make workflows entity aware
- [x] Add to workflow definition of existing workflow instance
- [x] Write migration guide
  - [x] Migrating the database
  - [x] Minimum Laravel Version
  - [x] Steps should use `WorkflowStepInterface`
  - [x] Replace `Workflow::define(...)` with `$this->define(...)`
- [x] Update documentation
  - [x] Update all examples to the new API
  - [x] Writing Plugins
  - [x] Optional `EntityAwareWorkflows` plugin
  - [x] Testing the `then` and `catch` callbacks of a workflow
  - [x] Define queue connection when starting a workflow
  - [x] Asserting that a workflow was started on a specific connection
  - [x] Adding jobs to an existing workflow instance
  - [x] Adding conditional jobs
  - [x] Depending on conditional jobs
  - [x] The callback passed to `assertStarted` now takes the job's queue connection as a second parameter
  - [x] Adding a closure to a workflow
  - [x] Gated jobs
  - [x] Staring a workflow synchronously
  - [x] Defining the queue connection for all jobs of a workflow
  - [x] Defining the queue for all jobs of a workflow
  - [x] Update section about testing workflows to use `WorkflowTester`
  - [x] Update section about inspecting workflow models to use state
  - [x] Customizing model states

## BC Breaks

This section is used to keep track of all BC breaks this version introduces. While I will try to keep them to a minimum and provide sensible migration paths, there are a few warts in the current implementation that require a BC break to really fix.

### Drop Laravel 8 support

Starting with 4.0, Venture will require Laravel 9.

### Jobs need to implement `WorkflowStepInterface`

~Since we can't type hint against traits, we currently have to resort to the `object` type whenever we're dealing with workflow jobs. Version 4.0 adds a proper interface and extends the existing `WorkflowStep` trait so it automatically implements the interface.~

~Since it's necessary to add `implements WorkflowStepInterface` to all existing workflow job classes, this is a BC break. We should be able to automate this with some sort of artisan command, however (e.g. `venture:migrate-jobs`). We basically have to look for classes that use the `WorkflowStep` trait and perform some kind of string replace on the class declaration.~

I found a way to make this backwards compatible for now. Instead, adding a job that doesn't implement the interface to a workflow will trigger a deprecation warning in version 4.

### `Workflow::define`  requires the workflow instance as the first parameter

Up until now, the `Workflow` facade's `define` method only took a `$name` parameter. In version 4, this method takes an instance of `AbstractWorkflow` as a parameter.

```diff
- Workflow::define('My workflow');
+ Workflow::define($this, 'My workflow');
```

This is so we can acces the actual workflow class inside plugins, instead of only dealing with the `WorkflowDefinition` class. This allows users to define extra properties/methods on their workflow classes which can then be used by various plugins.

As a convenience, the `AbstractWorkflow` class now provides a `define` method which automatically passes the current workflow instance to the `Workflow::define` method.

```diff
- Workflow::define('My workflow');
+ $this->define('My workflow');
```

Again, this is something we should be able to automate since it should be a rather straight-forward string replace.

### Changes to `WorkflowManagerInterface::startWorkflow` signature

The `WorkflowManagerInterface::startWorkflow` method now takes a second parameter `$connection` which specifies the connection to use for all jobs of the workflow. If `$connection` is null, it will use whatever default connection has been set on the job.

This is a fairly low-impact change as a I think it's unlikely that people will implement their own workflow manager or extend the default one. It is still a breaking change, however.

### `StepIdGenerator` needs to account for `WorkflowStepAdapter`

Jobs that don’t implement `WorkflowStepInterface` directly now get wrapped in a `WorkflowStepAdapter` class. This means that when implementing a custom `StepIdGenerator`, you now need to account for this class and potentially unwrap it before generating the id.

**Comment by Bariskau** [comment]
I'm looking forward to it using with laravel 9. @ksassnowski when do you plan to release?

**Comment by ksassnowski** [comment]
There is already a [release candidate available](https://github.com/ksassnowski/venture/releases/tag/4.0.0-RC3) that should be stable. I don't expect the actual code to change much until the release so this should be safe to use. In fact, I'm already using it in production.

The only thing that's still left is writing a few sections in the documentation.

**Comment by stevebauman** [comment]
Inside the new default `WorkflowState` classes, the `$workflow` property is private, so I'm not able to extend the `DefaultWorkflowState` and adjust one of the methods. Is this intended?

https://github.com/ksassnowski/venture/blob/2c8fc9d2e9503a18b4942507b99bc84695efa376/src/State/DefaultWorkflowState.php#L23

**Comment by ksassnowski** [comment]
Ah, you're right. It should probably be `protected`

**Comment by stevebauman** [comment]
Ok! Would you like me to submit a PR?

Going through the upgrade as we speak so I'll post here if I find anything else 👍

**Comment by ksassnowski** [comment]
Sounds good. You could maybe also double check if the same is true for the `DefaultWorkflowJobState`

**Comment by stevebauman** [comment]
`Workflow::getState()` is also private, so I'm not able to access it in my extended `Workflow`:

```php
class Workflow extends VentureWorkflow
{
    public function someMethod()
    {
        // $this->getState()
    }
}
```

**Comment by stevebauman** [comment]
Ah shoot sorry! I thought I was working off my own fork, but I pushed into `v4` directly 🙈 

https://github.com/ksassnowski/venture/commit/2aacd25c7da5c0fc8116bce21e2f4e323ae4b50b

**Comment by ksassnowski** [comment]
It's fine :+1:

**Comment by ksassnowski** [comment]
🎉 https://github.com/ksassnowski/venture/releases/tag/4.0.0
